# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30ba7f8dfb1890d353878e120d2cdc2f42ea12ab399b87ab48ed3460f5810518dac7e1598847e9dad935042ac4964a5b0e6701235983f12a3b66fcae2b386ed1

test:
  secret_key_base: a260a0a9826aaed5d1a59dd45100fa7a7d54f0838e62b483616fce8258c669035ad5fdd61da8656bf0252dfca80ff0f4aab293892fcd49f13db4f2bc11361d9b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
